# The URL the site will be built for
base_url = "https://www.christianfosli.com"
title = "Christian Fosli"
build_search_index = true
generate_feeds = true
compile_sass = true
taxonomies = [{ name = "tags" }]

theme = "apollo"

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
use_cdn = false
theme = "toggle"
comment = false

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
    { name = "/tags", url = "/tags", weight = 4 },
]

socials = [
    { name = "email", url = "mailto:cfosli@gmail.com", icon = "email" },
    { name = "email", url = "mailto:christian.fosli@webstep.no", icon = "email" },
    { name = "github", url = "https://github.com/christianfosli", icon = "github" },
    { name = "codeberg", url = "https://codeberg.org/christianfosli", icon = "code" },
    { name = "bluesky", url = "https://bsky.app/profile/christianfosli.com", icon = "bluesky" },
    { name = "linkedin", url = "https://www.linkedin.com/in/christianfosli", icon = "linkedin" },
    { name = "matrix", url = "https://matrix.to/#/@christianfosli:matrix.org", icon = "matrix" },
]

stylesheets = [
    "profilepic.css",
    "figures.css"
]

[extra.analytics]
enabled = false
